name: Continuous Deployment
on:
  push:
    branches: master
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: npm ci
      - name: Lint
        run: npm lint
  push_to_registry:
    name: Deploy New Version
    if: ${{ !contains(github.event.head_commit.message, '#skipDeploy') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build
        run: npm ci
      - name: Generate production bundle
        run: npm run build
      - name: Generate Tag
        uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@6c3ca5dfa6895029f82e5b2f26f060bc0d3c6a2c
        with:
          images: lopesdev/trashtalker-web
      - name: Build and Push Image
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
        with:
          context: .
          push: true
          tags: lopesdev/trashtalker-web:${{ steps.tag_version.outputs.new_tag }}
          labels: ${{ steps.meta.outputs.labels }}