name: Release npm package

on:
   workflow_dispatch:
      inputs:
         update_type:
            required: true
            description: patch/minor/major
            type: string
jobs:
   npm-publish:
      runs-on: ubuntu-latest
      steps:
         -  name: Generate webpack bundle
            env:
               ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               UPDATE_TYPE: ${{ inputs.update_type }}
            shell: bash
            run: |
               git config user.name medium-demo
               git config user.email medium-demo@github.com
               npm version $UPDATE_TYPE -m "Released new NPM package version: %s"
               echo "//npm.pkg.github.com/:authToken=$ACCESS_TOKEN" >> .npmrc
               npm i webpack
               npm run build
               npm publish
